"""Stub file for psycopg2.extras module."""

from typing import Any, Dict, List, Optional, Union
from typing_extensions import Protocol

class RealDictCursor(Protocol):
    def execute(self, query: str, vars: Any = ...) -> None: ...
    def fetchone(self) -> Optional[Dict[str, Any]]: ...
    def fetchall(self) -> List[Dict[str, Any]]: ...
    def fetchmany(self, size: int = ...) -> List[Dict[str, Any]]: ...

class DictCursor(Protocol):
    def execute(self, query: str, vars: Any = ...) -> None: ...
    def fetchone(self) -> Optional[Dict[str, Any]]: ...
    def fetchall(self) -> List[Dict[str, Any]]: ...
    def fetchmany(self, size: int = ...) -> List[Dict[str, Any]]: ...
