"""Stub file for psycopg2 module."""

from typing import Any, Optional, Union, Dict, List, Tuple
from typing_extensions import Protocol

class Connection(Protocol):
    def close(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def cursor(self, cursor_factory: Any = ...) -> Any: ...
    autocommit: bool

def connect(
    dsn: str = ...,
    connection_factory: Any = ...,
    cursor_factory: Any = ...,
    **kwargs: Any
) -> Connection: ...

class Error(Exception): ...
class DatabaseError(Error): ...
class OperationalError(DatabaseError): ...
class ProgrammingError(DatabaseError): ...
class IntegrityError(DatabaseError): ...
class InternalError(DatabaseError): ...
class NotSupportedError(DatabaseError): ...
